## Cosas a limpiar  
#### archivo bank-additional.csv
 
●   **age**: cambiar dato a tipo integer    
●	**job**:  la categoría  "admin." es la única que aparece abreviado, cambiar nombre a "administrative"    
●	**marital**: Catergorías en mayúsculas-> cambiar a minusculas  
●	**default**: estudiar el cambio a boolean, o Yes/No, ahora mismo es float   
●	**housing**: estudiar el cambio a boolean, o Yes/No, ahora mismo es float   
●	**loan**: estudiar el cambio a boolean, o Yes/No, ahora mismo es float    
●	**cons.price.idx**: cambiar a float. Cambiar puntos por guiones en el nombre de la columna  
●	**cons.conf.idx**: cambiar a float. Cambiar puntos por guiones en nombre de la columna    
●	**euribor3m**: cambiar a float   

●	**y**: estudiar cambioa  boolean    
●	**date**: cambio de a tipo fecha   
●	**contact_month**: conjunto de datos presenta columna latitude (no tiene sentido).Extraeremos estos datos de la columna 'date'    
●	**contact_year**: conjunto de datos presenta columna longitude (no tiene sentido). Extraeremos los datos de la columna 'date'     

#### Archivo customer-details.xlxs
El archivo parece tener datos consitentes

In [1]:
import pandas as pd
import numpy as np
import openpyxl
import locale
import sys
sys.path.append('../')
pd.set_option('display.max_columns', None)

In [17]:
df_raw=pd.read_csv('../data/b_additional_details.csv')

df=df_raw.copy()
df.sample(5)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth
34061,29.0,admin.,SINGLE,high.school,0.0,1.0,0.0,cellular,443,7,999,1,FAILURE,-1.8,"92,893","-46,2",NaN,"5099,1",yes,19-enero-2015,36.729,-84.444,104d4e65-ba97-41db-ac9b-dfc80c5af3e6,30522,0,0,2014-10-02,14
12091,NaN,services,SINGLE,professional.course,0.0,1.0,0.0,telephone,143,1,999,0,NONEXISTENT,1.4,"93,918","-42,7","4,955","5228,1",no,22-agosto-2015,36.553,-113.805,fd6bfd4b-47d1-4364-9e73-c365024c859c,53916,1,2,2012-02-27,23
27728,54.0,admin.,MARRIED,university.degree,0.0,0.0,0.0,cellular,47,2,999,0,NONEXISTENT,-1.8,"92,843",-50,"1,56","5099,1",no,15-agosto-2018,46.316,-114.381,d6272184-ddbb-44b7-b755-629e0a54a6e3,85304,0,1,2013-01-02,21
8194,NaN,blue-collar,MARRIED,basic.4y,0.0,1.0,1.0,telephone,495,3,999,0,NONEXISTENT,1.4,"94,465","-41,8","4,864","5228,1",no,10-septiembre-2016,32.541,-69.397,2c532a8a-ff5f-4dda-8513-ef8cd649fa9c,82252,0,2,2012-10-24,32
42269,36.0,technician,MARRIED,high.school,0.0,1.0,0.0,cellular,61,1,999,0,NONEXISTENT,1.4,"93,444","-36,1","4,965","5228,1",no,27-junio-2019,43.558,-102.706,a1ddb5ab-1178-4ecf-89f2-ec5b34c0bf22,17726,0,2,2014-10-09,28

## Cambios generales a nuestro DataFrame
Normalizamos los nombres y cambiamos de nombre las columnas latitud y longitud.
Los registro de las columnas tipo onject los pasamos a minusculas

In [18]:
df.columns= df.columns.str.replace('.','_').str.lower()

col_objetos=df.select_dtypes(include='object').columns
df[col_objetos]=df[col_objetos].apply(lambda col: col.str.lower())

### Cambio de columnas object de indices a float 
Cambiamos los datos que representan índices bursátiles y son tipo object a tipo float. Estos datos aparecen en las columnas 'cons_price_idx', 'cons_conf_idx', 'euribor3m'

In [4]:
col_index=['cons_price_idx', 'cons_conf_idx', 'euribor3m']
for col in col_index:
    df[col] = df[col].str.replace(',','.')
    df[col]=df[col].astype(float)
df.sample(5)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y,date,latitude,longitude,id_,income,kidhome,teenhome,dt_customer,numwebvisitsmonth
11253,38.0,technician,married,basic.9y,0.0,0.0,0.0,telephone,129,2,999,0,nonexistent,1.4,94.465,-41.8,4.961,"5228,1",no,29-agosto-2015,44.374,-101.663,6739c95f-411f-4629-9a15-d70162da7774,83488,0,1,2012-02-08,21
3209,53.0,blue-collar,married,basic.4y,0.0,0.0,0.0,telephone,198,3,999,0,nonexistent,1.1,93.994,-36.4,NaN,5191,no,21-junio-2015,25.742,-98.085,be331532-d837-42c1-9711-6d3ea4f0ae9d,78362,1,1,2012-11-29,1
11488,57.0,blue-collar,married,basic.4y,0.0,0.0,0.0,telephone,19,4,999,0,nonexistent,1.4,94.465,-41.8,4.959,"5228,1",no,23-noviembre-2017,47.979,-100.225,43a9094b-c0bd-40f0-a57c-b86603f0471f,101303,1,2,2012-06-07,26
27446,30.0,admin.,single,university.degree,0.0,0.0,0.0,cellular,331,2,999,0,nonexistent,-0.1,93.200,-42.0,NaN,"5195,8",yes,3-junio-2019,40.423,-78.615,6cab065c-6e14-4791-9238-aa8d8e86a8df,74113,1,2,2013-08-03,21
21210,47.0,admin.,married,university.degree,0.0,0.0,0.0,cellular,384,6,999,0,nonexistent,1.4,93.444,-36.1,NaN,"5228,1",yes,19-noviembre-2019,48.462,-97.418,0326ba78-750a-4b69-87dc-457ec035b045,130266,2,0,2013-10-13,20

## Limpieza de datos por columnas
### Columna `age`
Cambiar 'age' a tipo int

In [19]:
df['age']=df['age'].astype('Int64')
df['age'].describe().T

count      37880.0
mean     39.977112
std      10.437957
min           17.0
25%           32.0
50%           38.0
75%           47.0
max           98.0
Name: age, dtype: Float64

In [6]:
df['age'].isna().sum()

5120

Se deciden eliminar registros de datos edad nulos

In [7]:
df=df.dropna(subset=['age'])

### Columna `job`

In [20]:
df['job'].value_counts(dropna= False)

job
admin.           10873
blue-collar       9654
technician        7026
services          4162
management        3050
retired           1790
entrepreneur      1522
self-employed     1489
housemaid         1123
unemployed        1063
student            903
NaN                345
Name: count, dtype: int64

Cambiamos registros admin. por administrative en la columna job y creamos una nueva ategoría desconocido

In [21]:
df['job']=df['job'].replace({'admin.':'administrative'})
df['job']=df['job'].fillna('unknown')

### Columna `marital`

In [23]:
df['marital'].value_counts(dropna= False)

marital
married     25999
single      12105
divorced     4811
NaN            85
Name: count, dtype: int64

In [11]:
df['marital']=df['marital'].fillna('unknown')

### Columna `education`
Por consistencia la columna a los valores de la columna education, tambien le vamos a sustituir los . por _

In [24]:
df['education']=df['education'].str.replace('.','_')
df['education'].value_counts(dropna= False)

education
university_degree      12722
high_school             9925
basic_9y                6309
professional_course     5477
basic_4y                4356
basic_6y                2386
NaN                     1807
illiterate                18
Name: count, dtype: int64

In [25]:
df['education']=df['education'].fillna('unknown')

### Columna `default`,`default`, `housing`, `loan` y `y`
Estudiamos valores de la columna 'default', 'housing', 'loan' y 'y'. Las columnas datos son de tipo object y representan un numero 0.0  1.0, yes o no. Se valora el cambio de las columnas a tipo boolean, pero se desecha la opcion ya que los datos nulos se quieren seguir manteniendo como desconocidos. Por ellos las columnas seguirán siendo tiepo object, con valores yes, no, unknown.

In [26]:
col_bol=['default','housing', 'loan', 'y']

for col in col_bol:
  
    df[col] = df[col].replace(['unknown','nan','NaN'], np.nan)
    df[col] = df[col].map({'yes':'yes','no':'no','1':'yes','0':'no',1:'yes',0:'no'})
    df[col] = df[col].fillna('unknown')
    print(df[col].value_counts())

default
no         34016
unknown     8981
yes            3
Name: count, dtype: int64
housing
yes        22498
no         19476
unknown     1026
Name: count, dtype: int64
loan
no         35442
yes         6532
unknown     1026
Name: count, dtype: int64
y
no     38156
yes     4844
Name: count, dtype: int64

### Columna `date`
Cambiar 'date' a tipo fecha
Sustituimos los datos de latitud y longitud por los meses y años de la fecha date. Eliminamos la columna date ya que para nuestro análisis el día especifico que se realiza la contratación no es determinante y el resto de los datos de la fecha los tenemos ya guardados en otras columnas de nuestro df

In [27]:
locale.setlocale(locale.LC_TIME, 'Spanish_Spain') 
df['date'] = pd.to_datetime(df['date'], format='%d-%B-%Y')
df.columns=df.columns.str.replace('latitude','contact_month')
df['contact_month']=df['date'].dt.month.astype('Int64')
df.columns=df.columns.str.replace('longitude','contact_year')
df['contact_year']=df['date'].dt.year.astype('Int64')

df=df.drop(columns=['date'])

In [16]:
df.sample(10)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y,contact_month,contact_year,id_,income,kidhome,teenhome,dt_customer,numwebvisitsmonth
7888,39,services,divorced,high_school,unknown,yes,no,telephone,241,5,999,0,nonexistent,1.4,94.465,-41.8,4.865,"5228,1",no,9,2015,901830d5-07e7-429a-8c55-711b6190eb84,18319,2,0,2012-06-21,25
42792,38,administrative,married,high_school,no,yes,no,cellular,67,2,999,0,nonexistent,-0.1,93.200,-42.0,4.153,"5195,8",no,5,2015,61021b06-44df-4ef6-bd37-08b93e176d09,156346,1,0,2014-12-14,20
10866,28,administrative,married,university_degree,no,no,no,telephone,392,1,999,0,nonexistent,1.4,94.465,-41.8,4.962,"5228,1",no,2,2017,886a2864-ecec-4c03-8119-b76f43bfad9c,112933,2,0,2012-12-26,12
35369,45,services,divorced,high_school,no,no,no,cellular,15,9,999,1,failure,-1.8,92.893,-46.2,NaN,"5099,1",no,12,2016,dd1bd968-a906-4795-9d6f-89483965ebf3,40088,0,0,2014-07-27,10
2735,36,blue-collar,married,basic_6y,no,yes,no,telephone,57,1,999,0,nonexistent,1.1,93.994,-36.4,4.859,5191,no,6,2018,2d412bcb-c649-49ce-9137-e127ece69015,117293,2,1,2012-04-22,6
30448,59,retired,married,basic_4y,no,no,no,cellular,13,6,999,1,failure,-1.8,92.893,-46.2,1.354,"5099,1",no,4,2018,761118ac-1206-4e3d-9e2e-70e20311b6ae,149013,2,2,2014-02-16,4
34080,27,administrative,single,high_school,no,yes,yes,cellular,196,3,999,1,failure,-1.8,92.893,-46.2,1.281,"5099,1",no,1,2016,3e4e46d1-f669-44e5-98b0-7d1d89076cd4,32085,2,2,2014-08-07,19
12188,46,blue-collar,married,basic_9y,unknown,no,no,telephone,746,4,999,0,nonexistent,1.4,93.918,-42.7,4.966,"5228,1",no,1,2018,c4763ede-dc24-4388-ac47-b4f87b6093cc,117822,1,0,2012-03-27,29
32814,33,administrative,married,university_degree,no,no,yes,cellular,69,1,999,0,nonexistent,-1.8,92.893,-46.2,1.299,"5099,1",no,12,2019,733d70ea-781a-4a4e-a827-8a9c09ba606b,38956,0,2,2014-04-20,24
14471,35,blue-collar,divorced,basic_9y,no,yes,no,cellular,130,1,999,0,nonexistent,1.4,93.918,-42.7,4.961,"5228,1",no,6,2018,58daf4cb-c2ea-475b-9ac1-7439881fab1c,121738,2,1,2012-06-18,26