## Cosas a limpiar  
#### archivo bank-additional.csv
 
●   **age**: cambiar dato a tipo integer    
●	**job**:  la categoría  "admin." es la única que aparece abreviado, cambiar nombre a "administrative"    
●	**marital**: Catergorías en mayúsculas-> cambiar a minusculas  
●	**default**: estudiar el cambio a boolean, o Yes/No, ahora mismo es float   
●	**housing**: estudiar el cambio a boolean, o Yes/No, ahora mismo es float   
●	**loan**: estudiar el cambio a boolean, o Yes/No, ahora mismo es float    
●	**cons.price.idx**: cambiar a float. Cambiar puntos por guiones en el nombre de la columna  
●	**cons.conf.idx**: cambiar a float. Cambiar puntos por guiones en nombre de la columna    
●	**euribor3m**: cambiar a float   

●	**y**: estudiar cambioa  boolean    
●	**date**: cambio de a tipo fecha   
●	**contact_month**: conjunto de datos presenta columna latitude (no tiene sentido).Extraeremos estos datos de la columna 'date'    
●	**contact_year**: conjunto de datos presenta columna longitude (no tiene sentido). Extraeremos los datos de la columna 'date'     

#### Archivo customer-details.xlxs
El archivo parece tener datos consitentes

In [19]:
import pandas as pd
import numpy as np
import openpyxl
import locale
import sys
sys.path.append('../')
pd.set_option('display.max_columns', None)

In [20]:
df_raw=pd.read_csv('../data/b_additional_details.csv')

df=df_raw.copy()
df.sample(5)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth
9274,50.0,self-employed,MARRIED,university.degree,0.0,1.0,0.0,telephone,306,2,999,0,NONEXISTENT,1.4,"94,465","-41,8","4,967","5228,1",no,10-enero-2017,36.242,-109.638,18b17f03-3e47-4a4a-bbab-07dae39eecc2,111611,1,2,2012-06-28,29
3805,43.0,technician,DIVORCED,university.degree,NaN,0.0,0.0,telephone,62,2,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,858",5191,no,23-enero-2019,41.926,-117.355,0f4d849a-2b47-42d8-afef-edbf010c822c,34600,2,0,2012-08-13,24
40606,34.0,technician,SINGLE,university.degree,0.0,0.0,1.0,telephone,231,1,999,0,NONEXISTENT,-1.1,"94,199","-37,5","0,879","4963,6",yes,1-mayo-2015,37.984,-94.947,4a21bc64-088d-410c-bd47-e41b23a90430,23453,0,1,2014-02-05,20
13738,52.0,admin.,DIVORCED,high.school,NaN,0.0,0.0,cellular,67,1,999,0,NONEXISTENT,1.4,"93,918","-42,7","4,963","5228,1",no,27-diciembre-2016,44.500,-101.406,0298697d-c5b9-4c17-b6af-7bf0a1b54015,129097,2,1,2012-02-25,23
22866,60.0,retired,MARRIED,basic.4y,NaN,1.0,1.0,cellular,115,3,999,0,NONEXISTENT,1.4,NaN,"-36,1","4,965","5228,1",no,28-abril-2016,47.078,-98.706,5c072c09-fb35-434e-bc6f-20a7e7c89b95,109286,1,0,2013-12-21,17

## Cambios generales a nuestro DataFrame
Normalizamos los nombres y cambiamos de nombre las columnas latitud y longitud.
Los registro de las columnas tipo onject los pasamos a minusculas

In [21]:
df.columns= df.columns.str.replace('.','_').str.lower()

col_objetos=df.select_dtypes(include='object').columns
df[col_objetos]=df[col_objetos].apply(lambda col: col.str.lower())

### Cambio de columnas object de indices a float 
Cambiamos los datos que representan índices bursátiles y son tipo object a tipo float. Estos datos aparecen en las columnas 'cons_price_idx', 'cons_conf_idx', 'euribor3m'

In [22]:
col_index=['cons_price_idx', 'cons_conf_idx', 'euribor3m']
for col in col_index:
    df[col] = df[col].str.replace(',','.')
    df[col]=df[col].astype(float)
df.sample(5)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y,date,latitude,longitude,id_,income,kidhome,teenhome,dt_customer,numwebvisitsmonth
5635,30.0,blue-collar,single,basic.9y,NaN,1.0,1.0,telephone,225,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,no,14-junio-2015,35.941,-101.290,39541644-24f6-4818-be62-95ff019dd1de,91953,0,0,2012-05-05,12
336,36.0,technician,married,university.degree,0.0,0.0,0.0,telephone,210,1,999,0,nonexistent,1.1,93.994,-36.4,NaN,5191,no,27-octubre-2019,24.779,-109.056,251acb58-c500-41db-9820-1ad982d302b3,118942,1,0,2012-08-28,18
3176,40.0,admin.,married,high.school,NaN,1.0,0.0,telephone,299,1,999,0,nonexistent,1.1,93.994,-36.4,4.860,5191,no,8-febrero-2015,31.121,-100.632,45b5ff1f-6b59-4da4-9cb2-8e51ca2f2949,146802,2,2,2012-11-03,6
10162,52.0,NaN,married,basic.4y,0.0,0.0,0.0,telephone,253,2,999,0,nonexistent,1.4,94.465,-41.8,4.960,"5228,1",no,19-octubre-2018,31.464,-83.891,0a3371fe-4eb3-46bf-a090-6506f126b3ca,36767,1,0,2012-07-12,9
14247,50.0,blue-collar,married,basic.4y,0.0,0.0,0.0,cellular,244,3,999,0,nonexistent,1.4,93.918,-42.7,4.962,"5228,1",no,17-febrero-2015,48.538,-109.887,58383811-22d4-4cc5-8731-1b125605f939,78422,0,2,2012-02-11,1

## Limpieza de datos por columnas
### Columna `age`
Cambiar 'age' a tipo int

In [23]:
df['age']=df['age'].astype('Int64')
df['age'].describe().T

count      37880.0
mean     39.977112
std      10.437957
min           17.0
25%           32.0
50%           38.0
75%           47.0
max           98.0
Name: age, dtype: Float64

In [24]:
df['age'].isna().sum()

5120

Se deciden eliminar registros de datos edad nulos

In [25]:
df=df.dropna(subset=['age'])

Se crea columna grupos de edad (18-30/31-45/46-60/+60)

In [26]:
df["age_group"] = pd.cut(df["age"], bins=[18, 30, 45, 60, 100],labels=["18-30", "31-45", "46-60", "60+"])

### Columna `job`

In [27]:
df['job'].value_counts(dropna= False)

job
admin.           9564
blue-collar      8489
technician       6228
services         3627
management       2696
retired          1580
entrepreneur     1356
self-employed    1297
housemaid         990
unemployed        945
student           806
NaN               302
Name: count, dtype: int64

Cambiamos registros admin. por administrative en la columna job y creamos una nueva ategoría desconocido

In [28]:
df['job']=df['job'].replace({'admin.':'administrative'})
df['job']=df['job'].fillna('unknown')

### Columna `marital`

In [29]:
df['marital'].value_counts(dropna= False)

marital
married     22893
single      10652
divorced     4258
NaN            77
Name: count, dtype: int64

In [30]:
df['marital']=df['marital'].fillna('unknown')

### Columna `education`
Por consistencia la columna a los valores de la columna education, tambien le vamos a sustituir los . por _

In [31]:
df['education']=df['education'].str.replace('.','_')
df['education'].value_counts(dropna= False)

education
university_degree      11261
high_school             8734
basic_9y                5576
professional_course     4834
basic_4y                3837
basic_6y                2087
NaN                     1537
illiterate                14
Name: count, dtype: int64

In [32]:
df['education']=df['education'].fillna('unknown')

### Columna `default`,`default`, `housing`, `loan` y `y`
Estudiamos valores de la columna 'default', 'housing', 'loan' y 'y'. Las columnas datos son de tipo object y representan un numero 0.0  1.0, yes o no. Se valora el cambio de las columnas a tipo boolean, pero se desecha la opcion ya que los datos nulos se quieren seguir manteniendo como desconocidos. Por ellos las columnas seguirán siendo tiepo object, con valores yes, no, unknown.

In [33]:
col_bol=['default','housing', 'loan', 'y']

for col in col_bol:
  
    df[col] = df[col].replace(['unknown','nan','NaN'], np.nan)
    df[col] = df[col].map({'yes':'yes','no':'no','1':'yes','0':'no',1:'yes',0:'no'})
    df[col] = df[col].fillna('unknown')
    print(df[col].value_counts())

default
no         30002
unknown     7876
yes            2
Name: count, dtype: int64
housing
yes        19844
no         17122
unknown      914
Name: count, dtype: int64
loan
no         31206
yes         5760
unknown      914
Name: count, dtype: int64
y
no     33614
yes     4266
Name: count, dtype: int64

### Columna `date`
Cambiar 'date' a tipo fecha
Sustituimos los datos de latitud y longitud por los meses y años de la fecha date. Eliminamos la columna date ya que para nuestro análisis el día especifico que se realiza la contratación no es determinante y el resto de los datos de la fecha los tenemos ya guardados en otras columnas de nuestro df

In [34]:
locale.setlocale(locale.LC_TIME, 'Spanish_Spain') 
df['date'] = pd.to_datetime(df['date'], format='%d-%B-%Y')
df.columns=df.columns.str.replace('latitude','contact_month')
df['contact_month']=df['date'].dt.month.astype('Int64')
df.columns=df.columns.str.replace('longitude','contact_year')
df['contact_year']=df['date'].dt.year.astype('Int64')

df=df.drop(columns=['date'])

In [35]:
df.sample(10)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y,contact_month,contact_year,id_,income,kidhome,teenhome,dt_customer,numwebvisitsmonth,age_group
34133,34,blue-collar,divorced,basic_9y,unknown,yes,no,cellular,6,6,999,1,failure,-1.8,92.893,-46.2,1.266,"5099,1",no,8,2017,ce741f92-776b-4099-ac80-00c2dcf54016,76423,2,2,2014-10-27,21,31-45
24089,55,blue-collar,married,basic_9y,no,no,no,cellular,1077,1,999,0,nonexistent,-0.1,93.200,-42.0,NaN,"5195,8",yes,6,2015,f3386e20-17fd-4d12-bd3e-dc368d6c2193,121512,1,1,2013-01-18,16,46-60
9019,38,technician,married,professional_course,no,yes,no,telephone,220,2,999,0,nonexistent,1.4,94.465,-41.8,4.967,"5228,1",no,6,2016,4b0a35ba-3d97-42bf-8bc4-b9421d444939,47238,2,0,2012-10-15,17,31-45
6690,21,technician,single,professional_course,no,no,yes,telephone,109,2,999,0,nonexistent,1.1,93.994,-36.4,NaN,5191,no,4,2018,f99e560a-5869-42fe-8d47-34b2143524ba,166351,2,2,2012-03-08,22,18-30
15575,49,management,married,university_degree,no,yes,no,cellular,184,1,999,0,nonexistent,1.4,93.918,-42.7,NaN,"5228,1",no,4,2016,6b135be0-50eb-4def-af81-2ffc4c33c955,32610,1,1,2012-01-20,9,46-60
4749,46,entrepreneur,married,professional_course,no,yes,no,telephone,51,2,999,0,nonexistent,1.1,93.994,-36.4,4.858,5191,no,10,2015,13d43797-732b-4c01-a5c7-efbf42294607,69866,0,1,2012-08-01,23,46-60
6299,29,services,divorced,high_school,no,yes,no,telephone,50,3,999,0,nonexistent,1.1,93.994,-36.4,NaN,5191,no,3,2015,4bd7defe-056d-4034-be9f-f92f2d9bdd9a,71028,1,2,2012-04-21,25,18-30
26335,58,technician,married,professional_course,no,no,no,cellular,321,2,999,0,nonexistent,-0.1,93.200,-42.0,4.076,"5195,8",no,3,2017,d1368f3d-996b-4f33-8085-9b00e816a7cc,76667,1,2,2013-08-14,16,46-60
1950,49,technician,divorced,basic_9y,unknown,yes,no,telephone,185,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191,no,3,2018,1c74922f-415b-44a8-afb4-e8bf2b04c0ed,143794,2,0,2012-01-28,29,46-60
31620,32,administrative,married,high_school,no,no,yes,cellular,142,1,999,1,failure,-1.8,92.893,-46.2,NaN,"5099,1",no,5,2015,5a79d4ae-cf52-4c45-bd25-9320532fe44d,137231,2,1,2014-08-16,11,31-45

Guardamos los datos limpios

In [36]:
df.to_csv("../data/b_additional_details_clean.csv", index=False)