In [2]:
import pandas as pd
import numpy as np

import seaborn as sns
import openpyxl
import sys
sys.path.append('../')
pd.set_option('display.max_columns', None)

ModuleNotFoundError: No module named 'seaborn'

In [7]:
df=pd.read_csv('../data/b_additional_details_clean.csv')

In [8]:
df.describe(include="object")

,job,marital,education,default,housing,loan,contact,poutcome,nr_employed,y,id_,dt_customer,age_group
count,37880,37880,37880,37880,37880,37880,37880,37880,37880,37880,37880,37880,37847
unique,12,4,8,3,3,3,2,3,11,2,37880,1096,4
top,administrative,married,university_degree,no,yes,no,cellular,nonexistent,"5228,1",no,e9d37224-cb6f-4942-98d7-46672963d097,2012-08-10,31-45
freq,9564,22893,11261,30002,19844,31206,24122,32697,14969,33614,1,69,20197

Perfil de personal que suscribe  el producto

In [15]:
df.groupby("y")["age"].describe()

       count       mean        std   min   25%   50%   75%   max
y
no   33614.0  39.861724   9.920361  17.0  32.0  38.0  47.0  95.0
yes   4266.0  40.886310  13.823573  17.0  31.0  37.0  49.0  98.0

No hay gran diferencia en la media de edad entre personas que suscriben y no suscriben el producto

In [14]:
df.groupby("y")["education"].describe()

     count unique                top  freq
y
no   33614      8  university_degree  9733
yes   4266      8  university_degree  1528

In [ ]:
No hay diferencia

df.groupby("y")["duration"].mean()

In [16]:
df.groupby("y")["duration"].mean()

y
no     220.690813
yes    552.830989
Name: duration, dtype: float64